import time
from sympy.combinatorics import Permutation, PermutationGroup
from functions import enumerate_cube

# test runtime of implementation via sympy.combinatorics PermutationGroup

n = 3

if n % 2 == 0:
    N = 6 * n * n
else :
    N = 6 * n * n - 6

rubiks = enumerate_cube(n, N) # moves that generate the Rubik's cube
generators = rubiks

start_time = time.time()

G = PermutationGroup(list(generators)) # group generated by the moves
print(f"Group order: {G.order()}")

elapsed_time = time.time()-start_time
print(f"Time: {elapsed_time:.2f} seconds")